server:
  port: 8083

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

    gateway:
      routes:
        # 路由到订单服务
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        # 路由到用户服务
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
